//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        public Episode()
        {
            this.UserFeatureInfoes = new HashSet<UserFeatureInfo>();
        }
    
        public int id { get; set; }
        public int feature_id { get; set; }
        public Nullable<int> season { get; set; }
        public Nullable<int> episode1 { get; set; }
        public Nullable<int> title { get; set; }
        public string plot { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string imdb_id { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual ICollection<UserFeatureInfo> UserFeatureInfoes { get; set; }
    }
}
