//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public Feature()
        {
            this.Episodes = new HashSet<Episode>();
            this.UserFeatureInfoes = new HashSet<UserFeatureInfo>();
            this.Actors1 = new HashSet<Actor>();
            this.Genres = new HashSet<Genre>();
        }
    
        public int id { get; set; }
        public int feature_status_id { get; set; }
        public int type_id { get; set; }
        public string title { get; set; }
        public Nullable<int> year { get; set; }
        public string run_time { get; set; }
        public string genre { get; set; }
        public string director { get; set; }
        public string actors { get; set; }
        public string plot { get; set; }
        public string poster_url { get; set; }
        public Nullable<decimal> rating { get; set; }
        public string imdb_id { get; set; }
    
        public virtual ICollection<Episode> Episodes { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
        public virtual ICollection<UserFeatureInfo> UserFeatureInfoes { get; set; }
        public virtual ICollection<Actor> Actors1 { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
